# workflow reference
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: demo
on: [push]

jobs:
  prepare:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Create matrix ⊹
        id: prepare
        uses: ./
        with:
          n: 5

      - name: Print result 🖨
        run: echo '${{ steps.prepare.outputs.matrix }}'

  print:
    needs: [prepare]
    runs-on: ubuntu-20.04
    steps:
      - name: Print result 🖨
        run: echo '${{ needs.prepare.outputs.matrix }}'
