name: demo
on: [push]

jobs:
  prep:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Create matrix ⊹
        id: prepare
        uses: ./
        with:
          n: 5
